site_name: Education For Humans
nav:
  - Home: index.md
  - About: 
    - about.md
    - about/policies.md
    - about/working_groups.md
    - Diversity: about/diversity.md
  - Curriculum: 
    - Waldorf Education: curriculum/waldorfed.md
    - Nursery School: curriculum/nursery.md
    - Primary School: curriculum/primary.md
    - High School: curriculum/highschool.md
  - News&Events: 
    - Whats On: events.md
    - Leaflet: leaflet/latest.md
    - Community: community.md
  - Admissions: admissions.md
  - FAQ: faq.md
  - Contact: contact.md
theme: 
  name: spacelab #flatly #flatly #nature #spacelab flatly yeti slate

